# Canonical Minecraft 1.8.9 play/clientbound names -> Calamus gen2
net.minecraft.network.play.server.S08PacketPlayerPosLook=net.minecraft.unmapped.C_24866764
net.minecraft.network.play.server.S08PacketPlayerPosLook$EnumFlags=net.minecraft.unmapped.C_24866764$C_00540229
net.minecraft.network.play.server.S0EPacketSpawnObject=net.minecraft.unmapped.C_03408293
net.minecraft.network.play.server.S11PacketSpawnExperienceOrb=net.minecraft.unmapped.C_75007057
net.minecraft.network.play.server.S2CPacketSpawnGlobalEntity=net.minecraft.unmapped.C_55598986
net.minecraft.network.play.server.S0FPacketSpawnMob=net.minecraft.unmapped.C_78776045
net.minecraft.network.play.server.S10PacketSpawnPainting=net.minecraft.unmapped.C_35509806
net.minecraft.network.play.server.S0CPacketSpawnPlayer=net.minecraft.unmapped.C_18608044
net.minecraft.network.play.server.S0BPacketAnimation=net.minecraft.unmapped.C_44929569
net.minecraft.network.play.server.S37PacketStatistics=net.minecraft.unmapped.C_49919963
net.minecraft.network.play.server.S25PacketBlockBreakAnim=net.minecraft.unmapped.C_01281220
net.minecraft.network.play.server.S35PacketUpdateTileEntity=net.minecraft.unmapped.C_01827895
net.minecraft.network.play.server.S24PacketBlockAction=net.minecraft.unmapped.C_49472060
net.minecraft.network.play.server.S23PacketBlockChange=net.minecraft.unmapped.C_92666871
net.minecraft.network.play.server.S41PacketServerDifficulty=net.minecraft.unmapped.C_48841935
net.minecraft.network.play.server.S3APacketTabComplete=net.minecraft.unmapped.C_24802826
net.minecraft.network.play.server.S02PacketChat=net.minecraft.unmapped.C_47185453
net.minecraft.network.play.server.S22PacketMultiBlockChange=net.minecraft.unmapped.C_36877109
net.minecraft.network.play.server.S22PacketMultiBlockChange$BlockUpdateData=net.minecraft.unmapped.C_36877109$C_29575995
net.minecraft.network.play.server.S32PacketConfirmTransaction=net.minecraft.unmapped.C_31847740
net.minecraft.network.play.server.S2EPacketCloseWindow=net.minecraft.unmapped.C_43177000
net.minecraft.network.play.server.S2DPacketOpenWindow=net.minecraft.unmapped.C_37565076
net.minecraft.network.play.server.S30PacketWindowItems=net.minecraft.unmapped.C_78726810
net.minecraft.network.play.server.S31PacketWindowProperty=net.minecraft.unmapped.C_84972798
net.minecraft.network.play.server.S2FPacketSetSlot=net.minecraft.unmapped.C_75191757
net.minecraft.network.play.server.S3FPacketCustomPayload=net.minecraft.unmapped.C_96959155
net.minecraft.network.play.server.S40PacketDisconnect=net.minecraft.unmapped.C_67358769
net.minecraft.network.play.server.S19PacketEntityStatus=net.minecraft.unmapped.C_11134548
net.minecraft.network.play.server.S49PacketUpdateEntityNBT=net.minecraft.unmapped.C_03836274
net.minecraft.network.play.server.S27PacketExplosion=net.minecraft.unmapped.C_04411667
net.minecraft.network.play.server.S46PacketSetCompressionLevel=net.minecraft.unmapped.C_77048244
net.minecraft.network.play.server.S2BPacketChangeGameState=net.minecraft.unmapped.C_35876374
net.minecraft.network.play.server.S00PacketKeepAlive=net.minecraft.unmapped.C_26036426
net.minecraft.network.play.server.S21PacketChunkData=net.minecraft.unmapped.C_62858513
net.minecraft.network.play.server.S21PacketChunkData$Extracted=net.minecraft.unmapped.C_62858513$C_51190638
net.minecraft.network.play.server.S26PacketMapChunkBulk=net.minecraft.unmapped.C_96114107
net.minecraft.network.play.server.S28PacketEffect=net.minecraft.unmapped.C_20396934
net.minecraft.network.play.server.S2APacketParticles=net.minecraft.unmapped.C_53729405
net.minecraft.network.play.server.S29PacketSoundEffect=net.minecraft.unmapped.C_81132206
net.minecraft.network.play.server.S01PacketJoinGame=net.minecraft.unmapped.C_47909326
net.minecraft.network.play.server.S34PacketMaps=net.minecraft.unmapped.C_17555991
net.minecraft.network.play.server.S14PacketEntity=net.minecraft.unmapped.C_48216712
net.minecraft.network.play.server.S14PacketEntity$S15PacketEntityRelMove=net.minecraft.unmapped.C_48216712$C_47499961
net.minecraft.network.play.server.S14PacketEntity$S17PacketEntityLookMove=net.minecraft.unmapped.C_48216712$C_86577839
net.minecraft.network.play.server.S14PacketEntity$S16PacketEntityLook=net.minecraft.unmapped.C_48216712$C_26678328
net.minecraft.network.play.server.S36PacketSignEditorOpen=net.minecraft.unmapped.C_54246344
net.minecraft.network.play.server.S39PacketPlayerAbilities=net.minecraft.unmapped.C_52156807
net.minecraft.network.play.server.S42PacketCombatEvent=net.minecraft.unmapped.C_44609773
net.minecraft.network.play.server.S42PacketCombatEvent$1=net.minecraft.unmapped.C_44609773$77500029
net.minecraft.network.play.server.S42PacketCombatEvent$Event=net.minecraft.unmapped.C_44609773$C_56364878
net.minecraft.network.play.server.S38PacketPlayerListItem=net.minecraft.unmapped.C_70759607
net.minecraft.network.play.server.S38PacketPlayerListItem$1=net.minecraft.unmapped.C_70759607$89199269
net.minecraft.network.play.server.S38PacketPlayerListItem$Action=net.minecraft.unmapped.C_70759607$C_20916865
net.minecraft.network.play.server.S38PacketPlayerListItem$AddPlayerData=net.minecraft.unmapped.C_70759607$C_05019996
net.minecraft.network.play.server.S0APacketUseBed=net.minecraft.unmapped.C_29515286
net.minecraft.network.play.server.S13PacketDestroyEntities=net.minecraft.unmapped.C_97598839
net.minecraft.network.play.server.S1EPacketRemoveEntityEffect=net.minecraft.unmapped.C_89634238
net.minecraft.network.play.server.S48PacketResourcePackSend=net.minecraft.unmapped.C_89996999
net.minecraft.network.play.server.S07PacketRespawn=net.minecraft.unmapped.C_04694721
net.minecraft.network.play.server.S19PacketEntityHeadLook=net.minecraft.unmapped.C_10010951
net.minecraft.network.play.server.S44PacketWorldBorder=net.minecraft.unmapped.C_68445866
net.minecraft.network.play.server.S44PacketWorldBorder$1=net.minecraft.unmapped.C_68445866$69520838
net.minecraft.network.play.server.S44PacketWorldBorder$Action=net.minecraft.unmapped.C_68445866$C_49428745
net.minecraft.network.play.server.S43PacketCamera=net.minecraft.unmapped.C_43606595
net.minecraft.network.play.server.S09PacketHeldItemChange=net.minecraft.unmapped.C_62933986
net.minecraft.network.play.server.S3DPacketDisplayScoreboard=net.minecraft.unmapped.C_37218927
net.minecraft.network.play.server.S1CPacketEntityMetadata=net.minecraft.unmapped.C_42699272
net.minecraft.network.play.server.S1BPacketEntityAttach=net.minecraft.unmapped.C_37334942
net.minecraft.network.play.server.S12PacketEntityVelocity=net.minecraft.unmapped.C_27971442
net.minecraft.network.play.server.S04PacketEntityEquipment=net.minecraft.unmapped.C_21829382
net.minecraft.network.play.server.S1FPacketSetExperience=net.minecraft.unmapped.C_23223837
net.minecraft.network.play.server.S06PacketUpdateHealth=net.minecraft.unmapped.C_65195890
net.minecraft.network.play.server.S3BPacketScoreboardObjective=net.minecraft.unmapped.C_34303511
net.minecraft.network.play.server.S3EPacketTeams=net.minecraft.unmapped.C_05062620
net.minecraft.network.play.server.S3CPacketUpdateScore=net.minecraft.unmapped.C_61522066
net.minecraft.network.play.server.S3CPacketUpdateScore$Action=net.minecraft.unmapped.C_61522066$C_62637960
net.minecraft.network.play.server.S05PacketSpawnPosition=net.minecraft.unmapped.C_91575016
net.minecraft.network.play.server.S03PacketTimeUpdate=net.minecraft.unmapped.C_23459903
net.minecraft.network.play.server.S45PacketTitle=net.minecraft.unmapped.C_10931475
net.minecraft.network.play.server.S45PacketTitle$Type=net.minecraft.unmapped.C_10931475$C_23384688
net.minecraft.network.play.server.S33PacketUpdateSign=net.minecraft.unmapped.C_64282894
net.minecraft.network.play.server.S47PacketPlayerListHeaderFooter=net.minecraft.unmapped.C_48105049
net.minecraft.network.play.server.S0DPacketCollectItem=net.minecraft.unmapped.C_70193960
net.minecraft.network.play.server.S18PacketEntityTeleport=net.minecraft.unmapped.C_14614014
net.minecraft.network.play.server.S20PacketEntityProperties=net.minecraft.unmapped.C_28545193
net.minecraft.network.play.server.S20PacketEntityProperties$Snapshot=net.minecraft.unmapped.C_28545193$C_18557678
net.minecraft.network.play.server.S1DPacketEntityEffect=net.minecraft.unmapped.C_26792765
